### ISSUE TITLE
Predavanje projekta

### ISSUE THREAD

**Issue by NZivkovic94** [MATF-RG16/RG16-038-bilijar#5]
Projekat prenesen iz prethodne godine.

**Comment by ivan-cukic-matf** [comment]
Projekat se ne prenosi od prethodne godine. Morate ga doraditi.

**Comment by NZivkovic94** [comment]
Ja sam sa vama pricao o tome na pocetku semestra, samo mi nije bilo jasno na koji nacin mogu da doradim ovo. Mislio sam da je dovoljno da sredim ovo sto je bilo pod issues... Da li bi dovoljno bilo da napravim i da je sto 3D i da zakosim kameru? I da li cu ako to odradim pre 26og moci da izadjem tada na usmeni?
